region            = "ap-northeast-1"
env               = "shuhei"
service           = "test-go"
ver               = "latest"
global_ip_address = "58.93.220.180/32"
team              = "tse"
creator           = "shuhei_ogura@datadoghq.com"
dd_api_key        = ""
